Membership/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView



app_name = 'Membership'

urlpatterns = [
    path('register/', views.member_registration, name='register'),
    path('success/', views.successful, name='success'),
    path('create_account/', views.create_account, name='create_account'),
    path('lets-verify-you/', views.verification_view, name='lets-verify-you'),
    path('verified/', TemplateView.as_view(template_name='verification/verified.html'), name='verified'),
    path('pending/', TemplateView.as_view(template_name='verification/pending.html'), name='pending'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

OMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import re_path as url
from main.views import index_page
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
    path('', index_page, name='home'),
    path('offline/', TemplateView.as_view(template_name='offline.html'), name='offline'),
    path('page-not-found/', TemplateView.as_view(template_name='page_not_found.html'), name='page-not-found' ),
    path('verification-required/', TemplateView.as_view(template_name='verification/needs_to_be_verified.html'), name='verification-required'),
    path('payment/', include('payment.urls', namespace='payment')),
    path('main/', include('main.urls', namespace='main')),
    path('Membership/', include('Membership.urls', namespace='Membership')),
    path('Shares/', include('Share.urls', namespace='Share')),
    path('inAppDonations/', include('inAppDonations.urls', namespace='inAppDonations')),
    path('Loan_Request/', include('Loan_Request.urls', namespace='Loan_Request')),
    path('Monthly_due/', include('Monthly_due.urls', namespace='Monthly_due')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include('api.urls', namespace='api')),
    path('ads/', include('ads.urls', namespace='ads')),
    path('ecommerce/', include('ecommerce.urls', namespace='ecommerce')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('ommsclogs/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
#urls.py

from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from main import views



app_name = 'main'

urlpatterns = [
    path('about/', views.about_page, name='about'),
    path('contact/', views.contact_page, name='contact'),
    path('services/', views.services_page, name='services'),
    path('dashboard/', views.Dashboard, name='dashboard'),
    path('logout/', views.logout, name='logout'),
    path('user-profile-update/', views.ProfileEdit, name='user-profile-update'),
    path('registration-fee/', views.registration_fee_payment, name='registration-fee'),
    path('processing-payment/', views.payment_process, name='processing-payment'),
    path('payment-sucess/', views.payment_success, name='payment-success'),
    path('payment-canceled/', views.payment_canceled, name='payment-canceled'),
    path('youmade-payment_pdf/<pk>/pdf/', views.payment_pdf_generator, name='youmade-payment_pdf'),
    path('account_statement/', views.generate_account_statement, name='account_statement'),
    path('account_statement_pdf', views.account_statement_generate_pdf, name='account_statement_pdf'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/verification/needs_to_be_verified.html
{% extends 'navs/other_func_nav.html' %}

{% block content %}
<center>
    <div style="margin-top:50px;">
<button class='verification' 
style="border-radius: 50%; background-color:brown; 
width: 70px; height:70px; color:white; 
font-weight: bolder; border-style: none; margin-top: 20px;">
<i class="bi bi-wrong" style="font-weight: bolder; font-size:xx-large;"></i><br></button>
<legend style="font-family:'Courier New', Courier, monospace"><p>You Have To Be A
    <br>Verified Member To <br>Request A Loan.</p>
</legend>

<div>
    <a href="{% url 'Membership:lets-verify-you' %}">
        <button class='submit-btn'>Verifiy Me</button>
            </a>
    </div>
</div>
<div>
    <a href="{% url 'main:dashboard' %}">
        <button class="submit-btn">Close</button>
            </a>
    </div>
</center>

{% endblock %}

templates/verification/pending.html
{% extends 'navs/other_func_nav.html' %}

{% block content %}

<center>
    <div style="margin-top:50px ;">
    <button class='verification' style="border-radius: 50%; background-color:brown; 
    width: 70px; height:70px; color:white; 
    font-weight: bolder; border-style: none; margin-top: 20px;">
    <i class="bi bi-wrong" style="font-weight: bolder; font-size:xx-large;"></i><br></button>
    <legend style="font-family:'Courier New', Courier, monospace">Verification Pending!</legend>

    <div>
        <a href="{% url 'main:dashboard' %}">
            <button class="submit-btn">Close</button>
                </a>
        </div>
    </div>
</center>

{% endblock %}

templates/verification/verification.html
{% extends 'navs/dashboard_nav.html' %}


{% block content %}
{% load static %}

   <center>
    
    <section id="contact" class="verify-class">
      
        <form action="" method="post" role="form" class="php-email-form" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset>
          <button class='verification'
          style="border-radius: 50%; background-color:brown; 
          width: 70px; height:70px; color:white; 
          font-weight: bolder; border-style: none; margin-bottom: 20px;">
          <i class="bi bi-check" style="font-weight: bolder; font-size:xx-large;"></i><br></button>
          <legend style="font-family:'Courier New', Courier, monospace">Let's Verify You</legend>
          
            <div class="row">
          <div class="col-md-6 form-group">
            <span><i class="bi bi-phone"></i></span><span></span><b>Number</b><br/>
            <input type="text" name="phone-number" class="form-control" id="email" placeholder="Enter Phone Number" required>
          </div>
          <div class="col-md-6 form-group mt-3 mt-md-0">
            <span><i class="bi bi-person"></i></span><span></span><b>Government ID Type</b><br/>
            <input type="text" class="form-control" name="id-type" id="subject" list='ids' placeholder="Choose Id Type" required>
            <datalist id="ids">
              <option value="National Identification Number (NIN)">
                    <option value="Voter's Card">
              </datalist>
              </div>
        
          
            <div class="col-md-6 form-group">
            <p><img id="output" width="200"/></p>
            <span><i class="bi bi-camera"></i></span><span></span><b>Select ID Image</b><br/>
            <input type="file" name="id-image" accept="image/*" onchange="loadFile(event)" required>
           </div>
          </div>
                
           <div class="text-center"><button type="submit">Submit</button></div>
        </fieldset>
        </form>
        <div>
          <a href="{% url 'main:dashboard' %}">
              <button class="submit-btn">Close</button>
                  </a>
          </div>
        </section>
        </center>


{% endblock %}

templates/verification/verified.html
{% extends 'navs/other_func_nav.html' %}

{% block content %}
<center>
<div style="margin-top:50px;">
<button class="text-center"
style="border-radius: 50%; background-color:brown; 
width: 70px; height:70px; color:white; 
font-weight: bolder; border-style: none; margin-top: 20px;">
<i class="bi bi-check" style="font-weight: bolder; font-size:xx-large;"></i><br></button>
<legend style="font-family:'Courier New', Courier, monospace">You Have Been Verified!</legend>

<div>
<a href="{% url 'main:dashboard' %}">
    <button class="submit-btn">Close</button>
        </a>
</div>
</div>
</center>

{% endblock %}