OMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import re_path as url
from main.views import index_page
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
    path('', index_page, name='home'),
    path('offline/', TemplateView.as_view(template_name='offline.html'), name='offline'),
    path('page-not-found/', TemplateView.as_view(template_name='page_not_found.html'), name='page-not-found' ),
    path('verification-required/', TemplateView.as_view(template_name='verification/needs_to_be_verified.html'), name='verification-required'),
    path('payment/', include('payment.urls', namespace='payment')),
    path('main/', include('main.urls', namespace='main')),
    path('Membership/', include('Membership.urls', namespace='Membership')),
    path('Shares/', include('Share.urls', namespace='Share')),
    path('inAppDonations/', include('inAppDonations.urls', namespace='inAppDonations')),
    path('Loan_Request/', include('Loan_Request.urls', namespace='Loan_Request')),
    path('Monthly_due/', include('Monthly_due.urls', namespace='Monthly_due')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include('api.urls', namespace='api')),
    path('ads/', include('ads.urls', namespace='ads')),
    path('ecommerce/', include('ecommerce.urls', namespace='ecommerce')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('ommsclogs/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Share/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings


app_name = 'Shares'

urlpatterns = [
    path('share_dex/', views.share_holding, name='share_dex'),
    path('withdrawal_request/', views.withdrawal_request, name='withdrawal_request'),
    path('share_payment_view/', views.send_payment_for_share, name='share_payment_view'),
    path('shares_detail/', views.shares_detail_view, name='shares_detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
#urls.py

from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from main import views



app_name = 'main'

urlpatterns = [
    path('about/', views.about_page, name='about'),
    path('contact/', views.contact_page, name='contact'),
    path('services/', views.services_page, name='services'),
    path('dashboard/', views.Dashboard, name='dashboard'),
    path('logout/', views.logout, name='logout'),
    path('user-profile-update/', views.ProfileEdit, name='user-profile-update'),
    path('registration-fee/', views.registration_fee_payment, name='registration-fee'),
    path('processing-payment/', views.payment_process, name='processing-payment'),
    path('payment-sucess/', views.payment_success, name='payment-success'),
    path('payment-canceled/', views.payment_canceled, name='payment-canceled'),
    path('youmade-payment_pdf/<pk>/pdf/', views.payment_pdf_generator, name='youmade-payment_pdf'),
    path('account_statement/', views.generate_account_statement, name='account_statement'),
    path('account_statement_pdf', views.account_statement_generate_pdf, name='account_statement_pdf'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Share/models.py
from django.db import models
from django.conf import settings

# Create your models here.

percentage_calc = 100


class Payment_for_Share(models.Model):
    client_name = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, editable=False)
    amount = models.FloatField(default='0', editable=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    paid = models.BooleanField(default=False)
    payment_purpose = models.CharField(max_length=200)
    payment_ref = models.CharField(max_length=15, blank=True, editable=False)

    class Meta:
        ordering = ['-timestamp']

    def __str__(self):
        return f'Payment {self.id}'

    def get_amount(self):
        return self.amount

class ShareHolding(models.Model):
    client_name = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, editable=False)
    amount_bought = models.ForeignKey(Payment_for_Share, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True, editable=False)
    Share_return_at = models.FloatField(default=5, editable=False, help_text="Shares is at 5%")
    share_id = models.CharField(max_length=200, editable=False, default='0')
    there_was_a_withdrawal = models.BooleanField(default=False)


    class Meta:
        ordering = ['-timestamp']

    def __str__(self):
        return self.client_name.username

    def get_amount_of_shares(self):
        return self.amount_bought

    def get_date(self):
        return self.date_bought

    def investment_return(self):
        return self.Share_return_at / percentage_calc * self.amount_bought.amount

class Withdrawal_Request(models.Model):
    client_name = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, editable=False)
    share_id = models.CharField(max_length=200, editable=False, default='0')
    account_name = models.CharField(max_length=200, default='0')
    account_number = models.CharField(max_length=200, default='0')
    bank_name = models.CharField(max_length=200, default='0')
    timestamp = models.DateTimeField(auto_now_add=True)
    paid = models.BooleanField(default=False)

    def __str__(self):
        return self.client_name.username

Share/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from django.core.files.storage import FileSystemStorage
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User, auth
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from custom_code import pass_code as encrypter
from django.db.models import Q 
from django.forms.models import inlineformset_factory
from django.views.generic import ListView
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from Membership.models import Membership_verification

# Create your views here.


@login_required
def share_holding(request, *args, **kwargs):

    try:

        if Membership_verification.objects.filter(client_name=request.user).exists():
            obj = get_object_or_404(Membership_verification, client_name=request.user)
            
            if obj.verification_status == True:
                context = {}
                return render(request, 'shares/shares_index.html', context=context)

            elif obj.verification_status == False:
                return HttpResponseRedirect('/Membership/pending/') 
            else:
                return HttpResponseRedirect('/verification-required/')

    except SystemError as e:
        print('Error at'.format(e))
        
    context = {

    }

    return render(request, 'shares/shares_index.html', context=context)

@login_required
def send_payment_for_share(request, *args, **kwargs):

    context = {

    }

    return render(request, 'shares/shares_send_payment.html', context=context)


@login_required
def withdrawal_request(request, *args, **kwargs):
    
    context = {

    }

    return render(request, 'shares/withdrawal.html', context=context)

@login_required
def shares_detail_view(request, *args, **kwargs):
    
    context = {

    }

    return render(request, 'shares/shares_detail.html', context=context)

templates/shares/shares_detail.html
{% extends 'navs/other_func_nav.html' %}


{% block content %}
{% load static %}

<center style="margin-top:20px ;">
<h1>SHARES DETAIL</h1>

<a href="{% url 'Shares:withdrawal_request' %}"><button class="text-center">
    <i class="bi bi-briefcase"></i><br>Send Request <br> For Shares Withdrawal
</button>
</a>
</center>

<div>
    <center>
        <a href="{% url 'main:dashboard' %}">
        <button class="submit-btn">Close</button>
            </a>
    </center>
    </div>

{% endblock %}

templates/shares/shares_index.html
{% extends 'navs/other_func_nav.html' %}


{% block content %}
{% load static %}


<div class="shares_container">

<div class="row">
    <p class="top-check"><i class="bi bi-check"></i></p>
    <p><h3>One (1) Billion<br> Shares. <br> Buy @ &#8358;1 Per Share <br>(Min. &#8358;10,000 & Max. &#8358;1,000,000)</h3></p>
</div>

<div class="row-2">
<div class="list-of-shares-bought">
<a href="{% url 'Shares:shares_detail' %}"><button>YOUR <br> SHARES</button></a>
</div>

<div class="buy-shares">
    <a href="{% url 'Shares:share_payment_view' %}"><button>BUY SHARES</button></a>
</div>
<br/><br/>
    <a href="{% url 'main:dashboard' %}"><button class="submit-btn">Close</button></a>
</div>


</div>



{% endblock %}

templates/shares/shares_send_payment.html
{% extends 'navs/other_func_nav.html' %}


{% block content %}
{% load static %}

<center>
<h1 style="color:brown; font-weight:bolder; margin-top: 20px;">SHARES</h1>
<h4> Purchase of shares will be <br> open to the public soon!</h4>
</center>

<div>
    <a href="{% url 'main:dashboard' %}">
        <button class="submit-btn">Close</button>
            </a>
    </div>

{% endblock %}

templates/shares/withdrawal.html
{% extends 'navs/other_func_nav.html' %}


{% block content %}
{% load static %}

<center>
    <br/><br/>
    <h2>CASH WITHDRAWAL</h2>
    <br/><br/>
    <button class="text-center"
    style="border-radius: 50%; background-color:brown; 
    width: 70px; height:70px; color:white; 
    font-weight: bolder; border-style: none; margin-top: 20px;">
    <i class="bi bi-check" style="font-weight: bolder; font-size:xx-large;"></i><br></button>
    <br/><br/>
    <h4><b>Only For More Than<br>One Month Active Members</b></h4>
    <br/><br/>
    <a href="{% url 'main:dashboard' %}"><button class="submit-btn">Close</button></a>
</center>



{% endblock %}