OMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import re_path as url
from main.views import index_page
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
    path('', index_page, name='home'),
    path('offline/', TemplateView.as_view(template_name='offline.html'), name='offline'),
    path('page-not-found/', TemplateView.as_view(template_name='page_not_found.html'), name='page-not-found' ),
    path('verification-required/', TemplateView.as_view(template_name='verification/needs_to_be_verified.html'), name='verification-required'),
    path('payment/', include('payment.urls', namespace='payment')),
    path('main/', include('main.urls', namespace='main')),
    path('Membership/', include('Membership.urls', namespace='Membership')),
    path('Shares/', include('Share.urls', namespace='Share')),
    path('inAppDonations/', include('inAppDonations.urls', namespace='inAppDonations')),
    path('Loan_Request/', include('Loan_Request.urls', namespace='Loan_Request')),
    path('Monthly_due/', include('Monthly_due.urls', namespace='Monthly_due')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include('api.urls', namespace='api')),
    path('ads/', include('ads.urls', namespace='ads')),
    path('ecommerce/', include('ecommerce.urls', namespace='ecommerce')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('ommsclogs/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Share/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings


app_name = 'Shares'

urlpatterns = [
    path('share_dex/', views.share_holding, name='share_dex'),
    path('withdrawal_request/', views.withdrawal_request, name='withdrawal_request'),
    path('share_payment_view/', views.send_payment_for_share, name='share_payment_view'),
    path('shares_detail/', views.shares_detail_view, name='shares_detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
# myapp/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from .views import RegisterUser, LoginUser
from .views import (
    InAppDonationsDetail, InAppDonationsListView, 
    loan_request_listListView, ID_verification_ListView,
    Create_BranchListView,
    
)


app_name = 'api'

urlpatterns = [
    path('register/', RegisterUser.as_view(), name='register'),
    path('login/', LoginUser.as_view(), name='login'),
    path('inapp-donation/', InAppDonationsListView.as_view(), name="inapp-donation"),
    path('inapp-donation/<pk>/', InAppDonationsDetail.as_view(), name='inapp-donation'),
    path('loan-request/', loan_request_listListView.as_view(), name='loan-request'),
    path('id-verification/', ID_verification_ListView.as_view(), name='id-verification'),
    path('branches/', Create_BranchListView.as_view(), name='branches'),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
#urls.py

from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from main import views



app_name = 'main'

urlpatterns = [
    path('about/', views.about_page, name='about'),
    path('contact/', views.contact_page, name='contact'),
    path('services/', views.services_page, name='services'),
    path('dashboard/', views.Dashboard, name='dashboard'),
    path('logout/', views.logout, name='logout'),
    path('user-profile-update/', views.ProfileEdit, name='user-profile-update'),
    path('registration-fee/', views.registration_fee_payment, name='registration-fee'),
    path('processing-payment/', views.payment_process, name='processing-payment'),
    path('payment-sucess/', views.payment_success, name='payment-success'),
    path('payment-canceled/', views.payment_canceled, name='payment-canceled'),
    path('youmade-payment_pdf/<pk>/pdf/', views.payment_pdf_generator, name='youmade-payment_pdf'),
    path('account_statement/', views.generate_account_statement, name='account_statement'),
    path('account_statement_pdf', views.account_statement_generate_pdf, name='account_statement_pdf'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from payment.views import *




app_name = 'payment'

urlpatterns = [
    path('payment-gateway', payment, name='payment-gateway'),
    path('process', payment_process, name='process'),
    path('payment-sucess', payment_success, name='payment-success'),
    path('payment-canceled', payment_canceled, name='payment-canceled'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/about.html
{% extends 'navs/about_head.html' %}
{% load static %}


{% block content %}
    <!-- ======= About Section ======= -->
    <section id="about" class="about">
      <div class="container" data-aos="fade-up">

        <div class="row gy-4" data-aos="fade-up">
          <div class="col-lg-4">
            <img src="{% static 'assets/img/omslogo.png' %}" class="img-fluid" alt="">
          </div>
          <div class="col-lg-8">
            <div class="content ps-lg-5">
              <h3>We Are About: </h3>
              <p>
                OMMSC(Obidient Movement Multimedia Society Cooperative) based on the value of self-help, 
                self-responsibility, democracy, equality,
                equity, and solidarity. In the tradition of our founders,
                OMMCS members believe in the  ethical values of honesty, openness,
                social responsibility and caring for others
              </p>
              <ul>
                <li><i class="bi bi-check-circle-fill"></i>To promote self-help, self-reliance among members. </li>
                <li><i class="bi bi-check-circle-fill"></i> Gaining leadership and decision-making skills</li>
                <li><i class="bi bi-check-circle-fill"></i> Acquiring effective and efficient management</li>
                <li><i class="bi bi-check-circle-fill"></i>Increase members business engagement</li>
                <li><i class="bi bi-check-circle-fill"></i>Personal responsibility</li>
                <li><i class="bi bi-check-circle-fill"></i>Gaining confidence, self discipline and positive attitude</li>

              </ul>
            </div>
          </div>
        </div>

      </div>
    </section><!-- End About Section -->
  
  {% endblock %}


templates/contact.html
{% extends 'navs/contact_head.html' %}



{% block content %}
    <!-- ======= Contact Section ======= -->
    <section id="contact" class="contact">
      <div class="container position-relative">

          <div class="col-lg-6">

            <form action="" method="post" role="form" class="php-email-form">
              {% csrf_token %}
              <div class="row">
                <div class="col-md-6 form-group">
                  <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" required>
                </div>
                <div class="col-md-6 form-group mt-3 mt-md-0">
                  <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" required>
                </div>
              </div>
              <div class="form-group mt-3">
                <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" required>
              </div>
              <div class="form-group mt-3">
                <textarea class="form-control" name="message" rows="5" placeholder="Message" required></textarea>
              </div>

              <div class="text-center"><button type="submit">Send Message</button></div>
            </form>

          </div><!-- End Contact Form -->

        </div>

      </div>
    </section><!-- End Contact Section -->

    {% endblock %}

templates/dashboard.html
{% extends 'navs/dashboard_nav.html' %}


{% block content %}
{% load static %}

<section id='dashboard-section'>
    <div class="user-profile">
        <center>
            <div>
            <div>
            {% if user.is_authenticated %}
            <div>
                {% for item in profile_info %}
                {{item.profile_image}}

                {% empty %}
                <a href="" onclick="return false"><button class="dashboard-initial" id="profilepix">
                    {{ user | truncatechars:2 | first | capfirst }}
                    </button>
                    </a>
                {% endfor %}
            </div>
            Hello, {{user | capfirst}}<span>{% if verified_tag.verification_status is True %}
                    <i class="bi bi-check" style="font-weight: bolder; font-size:small;
                    margin-bottom: 0px; color:white; background-color: #922c17;
                    border-radius: 50%; border-style: none;"></i>
                    <br>
                {% else %}

                {% endif %}
            </span>
            {% endif %}
            </div>
            </div>
            <div>
                <button id="logout"><a href="{% url 'main:logout' %}">Logout</a></button>
            </div>
        </center>

        <center>
        <div id="acct-balance">
            <div>Your Acct Summary:</div></div></center>
        <div class="account-balance-row">
            <h5 class="h6-background">Donation:<br/>
                {% if total_amount_donations %}
                &#8358; {{total_amount_donations}}
                {% else %} 
                &#8358; 0.00</h5>
                {% endif %}
            <h5 class="h6-background">Shares:<br/> 
                &#8358; 0.00</h5>
            <h5 class="h6-background">Mnthly Due:<br/> 
                &#8358; 0.00</h5>
            <h5 class="h6-background">Loan:
                {% if total_loan_approved %}
                &#8358; {{total_loan_approved}}
                Return:&#8358; {{total_loan_approved_emi}} </h5>
                {% else %}
                &#8358; 0.00 <br/>
                {% endif %}
        </div>

    </div>
    <hr>
    <div class="dashboard-utils">
        <a href="{% url 'Loan_Request:loan-request' %}"><div class="message-us">
            <center>
            <i class="bi bi-briefcase">
            </i>
            <br><h6 style="font-size:x-small; font-weight: bolder;">Request <br>Loan</h6>
            </center>
    </div></a>

    <a href="{% url 'Membership:lets-verify-you' %}"><div class="get-verified"><center><i class="bi bi-check"></i>
                <br><h6 style="font-size:x-small; font-weight: bolder;">Get <br>Verified</h6></center>
    </div></a>

    <a href="{% url 'Monthly_due:home_monthly' %}"><div class="monthly-due"><center><i class="bi bi-clock"></i>
        <br><h6 style="font-size:x-small; font-weight: bolder;">Monthly<br> Due</h6></center>
    </div></a>

    <a href="{% url 'Share:share_dex' %}"><div class="message-us"><center><i class="bi bi-cash"></i>
        <br><h6 style="font-size:x-small; font-weight: bolder;">Shares & <br> Investment</h6></center>
    </div></a>

    <a href="{% url 'Share:withdrawal_request' %}"><div class="get-verified"><center><i class="bi bi-cash"></i>
            <br><h6 style="font-size:x-small; font-weight: bolder;">Withdrawal <br>Request</h6></center>
    </div></a>

    <a href="{% url 'inAppDonations:payment-gateway' %}"><div class="monthly-due"><center><i class="bi bi-heart"></i>
            <br><h6 style="font-size:x-small; font-weight: bolder;">Send <br>Donation</h6></center>
    </div></a>

    <a href="{% url 'main:account_statement' %}"><div class="monthly-due"><center><i class="bi bi-list"></i>
        <br><h6 style="font-size:x-small; font-weight: bolder;">Account <br>Statement</h6></center>
    </div></a>

    <a href=""><div class="monthly-due"><center><i class="bi bi-cash"></i>
        <br><h6 style="font-size:x-small; font-weight: bolder;">Top Up <br>Your Wallet</h6></center>
    </div></a>

    <a href="{% url 'ecommerce:product_list' %}"><div class="monthly-due"><center><i class="bi bi-cart"></i>
        <br><h6 style="font-size:x-small; font-weight: bolder;">Shop With<br>Us</h6></center>
    </div></a>
    
    </div>
    <hr>
    
           <!-- Ads section begins -->
           <div class="container">
            <div class="container">
                <h4>Your Ads</h4>
                <div class="row g-5 align-items-center">
                    <div class="col-md-12 col-lg-5">
                        <div id="carouselId" class="carousel slide position-relative" data-bs-ride="carousel">
                            <div class="carousel-inner" role="listbox">
                                <div class="carousel-item active rounded">
                                    <img src="{% static 'assets/img/ads.png' %}" class="img-fluid w-100 h-100 bg-secondary rounded" alt="First slide">
                                    <a href="#" class="btn px-4 py-2 text-white rounded"></a>
                                </div>
                                <div class="carousel-item rounded">
                                    <img src="{% static 'assets/img/ads.png' %}" class="img-fluid w-100 h-100 rounded" alt="Second slide">
                                    <a href="#" class="btn px-4 py-2 text-white rounded" ></a>
                                </div>
                            </div>
                            <button class="carousel-control-prev" type="button" data-bs-target="#carouselId" data-bs-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="visually-hidden">Previous</span>
                            </button>
                            <button class="carousel-control-next" type="button" data-bs-target="#carouselId" data-bs-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="visually-hidden">Next</span>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Ads section Ends -->
   </div>
</section>



{% endblock %}

templates/index.html
{% extends 'navs/index_head.html' %}


{% block content %}

{% endblock %}

templates/offline.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>OMMCSL- Dashboard</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  {% load static %}
  <!-- Favicons -->
  <link href="{% static 'assets/img/omslogo.png' %}" rel="icon">
  <link href="{% static 'assets/img/omslogo.png' %}" rel="apple-touch-icon">


  {% load static %}
  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">

  {% load static %}
  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/main.css' %}" rel="stylesheet">
  <link href="{% static 'assets/css/passcode.css' %}" rel="stylesheet">
  <link href="{% static 'assets/css/shares.css' %}" rel="stylesheet">
  <link href="{% static 'assets/css/inAppdonations.css' %}" rel="stylesheet">


</head>

<body class="page-contact" id="other-func-background">

  <!-- ======= Header ======= -->
  <header id="header" class="header d-flex align-items-center fixed-top">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

      <a href="{% url 'home' %}" onclick="alert('You are about to log out of your account.')" class="logo d-flex align-items-center">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <img src="{% static 'assets/img/omslogo.png' %}" alt="">
        <h1 class="d-flex align-items-center">OMMCSL</h1>
      </a>

      <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
      <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a href="{% url 'home' %}"><h6>Home</h6><i class="bi bi-house"></i></span></a></li>
          <li><a href="{% url 'main:about' %}"><h6>About</h6><i class="bi bi-book"></i></span></a></li>
          <li><a href="{% url 'main:services' %}"><h6>Services</h6><i class="bi bi-list"></i></span></a></li>         
          <li><a href="{% url 'Membership:register' %}"><h6>Register</h6><i class="bi bi-person"></i></span></a></li>
          <li><a href="{% url 'Loan_Request:loan-request' %}"><h6>Request Loan</h6><span><i class="bi bi-briefcase"></i></span></a></li>         
          <li><a href="{% url 'main:contact' %}"><h6>Message Us</h6><i class="bi bi-envelope"></i></span></a></li>
          <li><a href="{% url 'Membership:lets-verify-you' %}"><h6>Get Verified</h6><i class="bi bi-check"></i></span></a></li>
          <li><a href="{% url 'inAppDonations:payment-gateway' %}"><h6>Send Donation</h6><i class="bi bi-heart"></i></span></a></li>         
          <li><a href="{% url 'Shares:share_dex' %}"><h6>Shares</h6><i class="bi bi-cash"></i></span></a></li>
        </ul>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->

  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs d-flex align-items-center" 
    style="background-image: url({% static 'assets/img/hero-bg2.jpg' %});">
      <div class="container position-relative d-flex flex-column align-items-center">        

      </div>
    </div><!-- End Breadcrumbs -->


<center>

    <div class="">

        <h2 style="color:gray">
            <i>You are offline!</i></h2>
            <h6 style="color:gray">Please check your network</h6>
            <br/>
            <h1 style="color:gray"><strikethrought>OMMCSL</strikethrought>
            </h1>
            <h6 style="color:gray">OBidient Multipurpose Movement Cooperative Society.</h6>
            
        
            <br/><br/>
            <button type='button' class='offline-btn'>&#8635; reload</button>

        </div>

    </div>

</center>

</main>
<!-- ======= Footer ======= -->
<footer id="footer" class="footer">

<div class="footer-content">
 <div class="container">
   <div class="row gy-4">
     </div>

   
   </div>
 </div>
</div>

<div class="footer-legal fixed-bottom">
 <div class="container">
   
   <div class="copyright">
     <nav id="nav-bottom">
       <a href="{% url 'home' %}" class="bi bi-house"></a>
       <a href="{% url 'Loan_Request:loan-request' %}"> <i class="bi bi-briefcase"></i></a>
         <a href="{% url 'inAppDonations:payment-gateway' %}"><i class="bi bi-heart"></i></a>
           <a href="{% url 'Share:share_dex' %}"><i class="bi bi-cash"></i></a>
     </nav>         
     </div>
 </div>
</div>
</footer><!-- End Footer --><!-- End Footer -->

  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>
  <script src="{% static 'assets/js/newjs.js' %}"></script>
  <script src="{% static 'assets/js/offline.js' %}"></script>
  <script src="{% static 'assets/js/serviceworker.js' %}"></script>

</body>

</html>

templates/page_not_found.html
{% extends 'navs/page-note-found.html' %}


{% block content %}

{% endblock %}

templates/services.html
{% extends 'navs/services_head.html' %}



{% block content %}
    <!-- ======= Our Services Section ======= -->
    <section id="services-list" class="services-list">
      <div class="container" data-aos="fade-up">

        <div class="section-header">
          <h2>Our Services</h2>

        </div>

        <div class="row gy-5">

          <div class="col-lg-4 col-md-6 service-item d-flex" data-aos="fade-up" data-aos-delay="100">
            <div class="icon flex-shrink-0"><i class="bi bi-check" style="color: #f57813;"></i></div>
            <div>
              <h4 class="title"><a href="#" class="stretched-link">Good & Services</a></h4>
              <p class="description">To provide goods and services to our members at a reasonable cost with the aim to encourage them towards productivity,
                savings, investments and equal distribution of surplus.
              </p>
            </div>
          </div>
          <!-- End Service Item -->

          <div class="col-lg-4 col-md-6 service-item d-flex" data-aos="fade-up" data-aos-delay="200">
            <div class="icon flex-shrink-0"><i class="bi bi-check" style="color: #15a04a;"></i></div>
            <div>
              <h4 class="title"><a href="#" class="stretched-link">Managing Funds</a></h4>
              <p class="description">To mobilize funds and savings among members.</p>
            </div>
          </div><!-- End Service Item -->

          <div class="col-lg-4 col-md-6 service-item d-flex" data-aos="fade-up" data-aos-delay="300">
            <div class="icon flex-shrink-0"><i class="bi bi-check" style="color: #d90769;"></i></div>
            <div>
              <h4 class="title"><a href="#" class="stretched-link">Moderate Rate</a></h4>
              <p class="description">To provide consumer goods to members at reasonable rates.</p>
            </div>
          </div><!-- End Service Item -->

          <div class="col-lg-4 col-md-6 service-item d-flex" data-aos="fade-up" data-aos-delay="400">
            <div class="icon flex-shrink-0"><i class="bi bi-check" style="color: #15bfbc;"></i></div>
            <div>
              <h4 class="title"><a href="#" class="stretched-link">Personification</a></h4>
              <p class="description">To provide services to members according to their needs, such as housing, transport,
              insurance etc.
              </p>
            </div>
          </div><!-- End Service Item -->

          <div class="col-lg-4 col-md-6 service-item d-flex" data-aos="fade-up" data-aos-delay="500">
            <div class="icon flex-shrink-0"><i class="bi bi-check" style="color: #f5cf13;"></i></div>
            <div>
              <h4 class="title"><a href="#" class="stretched-link">Growth</a></h4>
              <p class="description">To promote self-help, self-reliance among members.</p>
            </div>
          </div><!-- End Service Item -->

          <div class="col-lg-4 col-md-6 service-item d-flex" data-aos="fade-up" data-aos-delay="600">
            <div class="icon flex-shrink-0"><i class="bi bi-check" style="color: #1335f5;"></i></div>
            <div>
              <h4 class="title"><a href="#" class="stretched-link">Trainings</a></h4>
              <p class="description">Gaining leadership and decision-making skills.</p>
            </div>
          </div><!-- End Service Item -->

        </div>

      </div>
    </section><!-- End Our Services Section -->

  {% endblock %}

templates/statement.html
{% extends 'navs/other_func_nav.html' %}
{% load static %}


{% block content %}



<div style="margin: 10px; padding: 5px; margin-top: 60px; color:#922c17">
    <center>
        <div>
            <img src="{% static 'assets/img/omslogo.png' %}" width='100' height='100'>
        </div>
        <h4>OMMCSL - Statement of Account</h4>
    </center>

    <hr>
    <div style="margin-top:15px; margin-bottom:15px;">
        <table class="statement_table">
    <h4><u>Donations</u></h4>
            <thead>
                <tr style="margin-right: 20px ;">
                    <th>Name</th>
                    <th>Amount</th>
                    <th>Time Stamp</th>
                </tr>
            </thead>
        <tbody>
{% for i in inappdonation_transactions%}

            <tr>
                <td>{{i.client_name}}</td>
                <td>&#8358;{{i.amount}}</td>
                <td>{{i.timestamp}}</td>
            </tr>
            </tbody>
{% empty %}
<p><ul>
    <li>There is no transaction history</li>
    </ul></p>
{% endfor %}
</table>
</div>

<hr>
<div style="margin-top:15px; margin-bottom:15px;">
    <table class="">
        <h4><u>Loan Statement</u></h4>
                <thead>
                    <tr style="margin-right: 20px;">
                        <th>Name</th>
                        <th>Amount</th>
                        <th>Timestamp</th>
                    </tr>
                </thead>
            <tbody>
                {% for i in loan_request_transactions%}
                <tr>
                    <td>{{i.client_name}}</td>
                    <td>&#8358;{{i.loan_amount}}</td>
                    <td>{{i.emi}}</td>
                    <td>{{i.timestamp}}</td>
                </tr>
                </tbody></table>
    {% empty %}
    <p><ul>
        <li>There is no transaction history</li>
        </ul></p>
    {% endfor %}

</div>

<hr>
<div style="margin-top:15px; margin-bottom:15px;">
    <h4><u>Shares</u></h4>
    <table>
        <thead>
            <tr style="margin-right: 20px ;">
                <th>Name</th>
                <th>Amount</th>
                <th>Time Stamp</th>
            </tr>
        </thead>
    <tbody>
{% for i in shares_transactions%}
        <tr class="statement_table">
            <td>{{i.client_name}}</td>
            <td>&#8358;{{i.amount}}</td>
            <td>{{i.timestamp}}</td>
        </tr>
        </tbody>
{% empty %}
<p><ul>
    <li>There is no transaction history</li>
    </ul></p>
{% endfor %}
</table>
</div>

</div>

<hr>
<div style="margin: 10px; padding: 5px; color: black">
    <table>
        <thead>
            <tr>
                <th>Total Amount Transacted history</th>
            </tr>
        </thead>
        <tbody>
            {% if overall_total %}
            <tr>
                <td> &#8358;{{overall_total}}</td>
            </tr>
        </tbody></table>
    {% endif %}
</div>

<hr>

<a href="{% url 'main:account_statement_pdf' %}"><button class="submit-btn" style="margin-top: 30px;">Download</button></a>
<hr>
<a href="{% url 'main:dashboard' %}"><button class="submit-btn" style="margin-top: 30px;">Close</button></a>

{% endblock %}

templates/thanks.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>OMMSCL- Dashboard</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  {% load static %}
  <!-- Favicons -->
  <link href="{% static 'assets/img/omslogo.png' %}" rel="icon">
  <link href="{% static 'assets/img/omslogo.png' %}" rel="apple-touch-icon">


  {% load static %}
  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">

  {% load static %}
  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/main.css' %}" rel="stylesheet">
  <link href="{% static 'assets/css/passcode.css' %}" rel="stylesheet">
  <link href="{% static 'assets/css/shares.css' %}" rel="stylesheet">
  <link href="{% static 'assets/css/inAppdonations.css' %}" rel="stylesheet">


</head>



<body>

<center style="margin-top: 100px">
    <button class="text-center"
style="border-radius: 50%; background-color:brown; 
width: 70px; height:70px; color:white; 
font-weight: bolder; border-style: none; margin-top: 20px;">
<i class="bi bi-check" style="font-weight: bolder; font-size:xx-large;"></i><br></button>
    
    <p><h1 style="font-weight: bolder;">Thank you!</h1></p>

    <p><h2>It's was Successful!</h2></p>

</center>

<!-- For page redirection after stipulate time -->
<meta http-equiv="refresh" content="6, url={% url 'home' %}">

</body>


</html>


 