OMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import re_path as url
from main.views import index_page
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
    path('', index_page, name='home'),
    path('offline/', TemplateView.as_view(template_name='offline.html'), name='offline'),
    path('page-not-found/', TemplateView.as_view(template_name='page_not_found.html'), name='page-not-found' ),
    path('verification-required/', TemplateView.as_view(template_name='verification/needs_to_be_verified.html'), name='verification-required'),
    path('payment/', include('payment.urls', namespace='payment')),
    path('main/', include('main.urls', namespace='main')),
    path('Membership/', include('Membership.urls', namespace='Membership')),
    path('Shares/', include('Share.urls', namespace='Share')),
    path('inAppDonations/', include('inAppDonations.urls', namespace='inAppDonations')),
    path('Loan_Request/', include('Loan_Request.urls', namespace='Loan_Request')),
    path('Monthly_due/', include('Monthly_due.urls', namespace='Monthly_due')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include('api.urls', namespace='api')),
    path('ads/', include('ads.urls', namespace='ads')),
    path('ecommerce/', include('ecommerce.urls', namespace='ecommerce')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('ommsclogs/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static





app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from ecommerce.views import SearchResultView



app_name = 'ecommerce'


urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('search/', views.SearchResultView.as_view(), name='search_results'),
    path('create/', views.order_create, name='order_create'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

ecommerce/models.py
from django.db import models
# Create your models here.
from django.urls import reverse
from django.conf import settings
from django.db import models




class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('ecommerce:product_list_by_category', args=[self.slug])

    def __str__(self):
        return self.name
    



class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    discount_available = models.BooleanField(default=False)
    discount_price = models.FloatField(blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image2 = models.FileField(upload_to='products/%Y/%m/%d', blank=True)
    image3 = models.FileField(upload_to='products/%Y/%m/%d', blank=True)

    class Meta:
        ordering = ('-created',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('ecommerce:product_detail', args=[self.id, self.slug])


class Order(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    class Meta:
        ordering = ('-created',)
    def __str__(self):
        return f'Order {self.id}'
    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())

class OrderItem(models.Model):
    order = models.ForeignKey(Order,
                              related_name='items',
                              on_delete=models.CASCADE)
    product = models.ForeignKey(Product,
                                related_name='order_items',
                                on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)
    def __str__(self):
        return str(self.id)
    def get_cost(self):
        return self.price * self.quantity


class Review(models.Model): 
    post = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='products')
    name = models.CharField(max_length=80)
    email = models.CharField(max_length=200, default='None')
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('-created',)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('ecommerce:product_detail', kwargs = {'pk' : self.pk})

ecommerce/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address',
                  'postal_code', 'city']

cart/views.py
from django.shortcuts import render
# Create your views here.
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from ecommerce.models import Product
from .cart import Cart
from .form import CartAddProductForm
import json
from django.contrib import messages


@require_POST
def cart_add(request, product_id):
    try:
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        new = list(Product.objects.values('id'))
        form = CartAddProductForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            cart.add(new=new,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])
        return redirect('cart:cart_detail')
    except:
        message = messages.info(request, 'There was an error')
        return('ecommerce:product_list')



@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
                            'quantity': item['quantity'],
                            'override': True})
    return render(request, 'ecommerce/cart.html', {'cart': cart})

ecommerce/views.py
from django.shortcuts import render
# Create your views here.
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from .models import Category, Product, Review
from django.views.generic import ListView, DetailView
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect
from django.views import View
from cart.form import CartAddProductForm
from django.shortcuts import render
from .models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    paginator = Paginator(products, 40) #for paginator to display items on each page
    page = request.GET.get('page')
    try:
        page_obj = paginator.get_page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        page_obj = paginator.get_page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        page_obj = paginator.get_page(paginator.num_pages)

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    context = {
        'category': category,
        'categories': categories,
        'products': products,
        'page' : page,
        'page_obj' : page_obj,
    }
    return render(request, 'ecommerce/ecommerce.html', context=context)


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    reviews = product.products.filter(active=True, post_id=id)

    if request.method == 'POST':
        name = request.POST['username']
        email = request.POST['email']
        body = request.POST['comments']

        new_review = Review.objects.get_or_create(
            post = product,
            name = name,
            email = email,
            body = body
        )

        if new_review:
            review_message = messages.info(request, 'Your review has been posted')

    context = {
        'product' : product,
        'cart_product_form' : cart_product_form,
        'reviews' : reviews, 
    }

    return render(request, 'ecommerce/productDetail.html', context=context)


class SearchResultView(ListView):

    model = Product
    template_name = 'ecommerce/search.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = Product.objects.filter(
            Q(description__icontains=query) | Q(name__icontains=query)
        )
        return object_list


def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                        product=item['product'],
                                        price=item['price'],
                                        quantity=item['quantity'])
            # clear the cart
            cart.clear()
            return render(request,
                          'ecommerce/create.html',
                          {'order': order})
    else:
        form = OrderCreateForm()
    return render(request,
                  'ecommerce/create.html',
                  {'cart': cart, 'form': form})

templates/ecommerce/cart.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <title>OMMCSL- Cart</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="" name="keywords">
        <meta content="" name="description">

        <!-- Google Web Fonts -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Raleway:wght@600;800&display=swap" rel="stylesheet"> 

         <!-- Icon Font Stylesheet -->
         <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"/>
         <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
        
         {% load static %}
         <!-- Libraries Stylesheet -->
         <link href="{% static 'assets/lib/lightbox/css/lightbox.min.css' %}" rel="stylesheet">
         <link href="{% static 'assets/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
 
         {% load static %}
         <!-- Customized Bootstrap Stylesheet -->
         <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet">
         
         {% load static %}
         <!-- Template Stylesheet -->
         <link href="{% static 'assets/css/ecom.css' %}" rel="stylesheet">
    </head>

    <body>
   <!-- Spinner Start -->
   <div id="spinner" class="show w-100 vh-100 bg-white position-fixed translate-middle top-50 start-50  d-flex align-items-center justify-content-center">
    <div class="spinner-grow" style="color:#922c17;" role="status"></div>
    </div>
    <!-- Spinner End -->

    <!-- Modal Search Start -->
        <div class="modal fade" id="searchModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-fullscreen">
                <div class="modal-content rounded-0">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Search by keyword</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body d-flex align-items-center">
                        <form method="">
                        <div class="input-group w-75 mx-auto d-flex">
                            <input type="search" class="form-control p-3" placeholder="keywords" aria-describedby="search-icon-1">
                            <span id="search-icon-1" class="input-group-text p-3"><i class="fa fa-search"></i></span>
                        </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- Modal Search End -->
        
       <!-- Top bar items -->   
       <div class="d-flex m-3 me-0 py-3">
        <button class="btn-search btn border btn-md-square rounded-circle bg-white me-4" data-bs-toggle="modal" data-bs-target="#searchModal">
            <i class="fas fa-search" style="color:#922c17;"></i></button>
        <a href="{% url 'cart:cart_detail' %}" class="position-relative me-4 my-auto">
            {% with total_items=cart|length %}
            {% if total_items > 0 %}
              <a href="{% url 'cart:cart_detail' %}">
                <i class="fa fa-shopping-bag fa-2x" style="color:#922c17"></i>
                <span class="position-absolute rounded-circle d-flex align-items-center justify-content-center text-white px-1" 
                style="top: -5px; left: 15px; height: 20px; min-width: 20px; color:#922c17; background-color:#922c17;">
                {{ total_items }} item{{ total_items|pluralize }},
                </span>    
               <!--  ${{ cart.get_total_price }} -->
              </a>
            {% else %}
            <i class="fa fa-shopping-bag fa-2x" style="color:#922c17"></i>
            <span class="position-absolute rounded-circle d-flex align-items-center justify-content-center text-white px-1" 
            style="top: -5px; left: 15px; height: 20px; min-width: 20px; color:#922c17; background-color:#922c17;">0</span>
            </a>
            {% endif %}
            {% endwith %}
            <a href="{% url 'ecommerce:product_list' %}" class="my-auto" style="color:#922c17">
                <i class="fas fa-home fa-2x"></i>
            </a>
        </div>
        <hr>

      <!-- Single Page Header start -->
    <div class="container" style="background-color: #922c17">
        <h1 class="text-center text-white display-6">Cart</h1>
    </div> 
    <!-- Single Page Header End -->
        
    <!-- End of top bar item -->

        <!-- Cart Page Start -->
        <div class="container">
            <div class="container">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                          <tr>
                            <th scope="col">Products</th>
                            <th scope="col">Name</th>
                            <th scope="col">Price</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Total</th>
                            <th scope="col">Handle</th>
                          </tr>
                        </thead>
                        <tbody>
                            {% for item in cart %}
                            {% with product=item.product %}
                            <tr>
                                <th scope="row">
                                    <div class="d-flex align-items-center">
                                        <a href="{{ product.get_absolute_url }}">
                                            <img src="{% if product.image %}{{ product.image.url }}
                                            {% else %}{% static 'assets/img/no_image.png' %}{% endif %}"
                                            class="img-fluid me-5 rounded-circle" style="width: 80px; height: 80px;" alt="">
                                          </a>
                                    </div>
                                </th>
                                <td>
                                    <p class="mb-0 mt-4">{{ product.name }}</p>
                                </td>
                                <td>
                                    <p class="mb-0 mt-4">&#8358;{{ item.price }}</p>
                                </td>
                                <td>
                                    <td>
                                        <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                          {{ item.update_quantity_form.quantity }}
                                          {{ item.update_quantity_form.override }}
                                          <input type="submit" value="Update">
                                          {% csrf_token %}
                                        </form>
                                      </td>
                                      
                                </td>
                                <td>
                                   
                                  </td>
                                <td>
                                    <p class="mb-0 mt-4">&#8358;{{ item.total_price }}</p>
                                </td>
                                <td>
                                    <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-md rounded-circle bg-light border mt-4" >
                                            <i class="fa fa-times text-danger"></i>
                                        </button>
                                      </form>
                                </td>
                            </tr>
                        </tbody>
                        {% endwith %}
                        {% endfor %}
                    </table>
                </div>
                <!-- Continue shopping -->
                <div class="mt-5">
                    <a href="{% url 'ecommerce:product_list' %}" class="button light">
                    <button class="btn border-danger rounded-pill px-4 py-3 text-danger" type="button">Continue shopping</button>
                    </a>
                </div>
                <!-- Coupon form -->
                <form>
                <div class="mt-5">
                    <input type="text" class="border-0 border-bottom rounded me-5 py-3 mb-4" placeholder="Coupon Code">
                    <button class="btn border-danger rounded-pill px-4 py-3 text-danger" type="button">Apply Coupon</button>
                </div>
                </form>
                <!-- End of Coupon form -->
                <div class="row g-4 justify-content-end">
                    <div class="col-8"></div>
                    <div class="col-sm-8 col-md-7 col-lg-6 col-xl-4">
                        <div class="bg-light rounded">
                            <div class="p-4">
                                <h1 class="display-6 mb-4">Cart <span class="fw-normal">Total</span></h1>
                                <div class="d-flex justify-content-between mb-4">
                                    <h5 class="mb-0 me-4">Subtotal:</h5>
                                    <p class="mb-0">&#8358;{{ item.total_price }}</p>
                                </div>
                                <div class="d-flex justify-content-between">
                                    <h5 class="mb-0 me-4">Delivery</h5>
                                    <div class="">
                                        <p class="mb-0">Fee: &#8358;0</p>
                                    </div>
                                </div>
                                <p class="mb-0 text-end">Delivery to </p>
                            </div>
                            <div class="py-4 mb-4 border-top border-bottom d-flex justify-content-between">
                                <h5 class="mb-0 ps-4 me-4">Total</h5>
                                <p class="mb-0 pe-4">&#8358;{{ cart.get_total_price }}</p>
                            </div>
                            <a href="{% url 'ecommerce:order_create' %}">
                            <button class="btn border-danger rounded-pill px-4 py-3 text-danger text-uppercase mb-4 ms-4" type="button">
                                Proceed Checkout</button></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Cart Page End -->

   <!-- Footer Start -->
   <div class="container-fluid text-white-50 footer pt-2 mt-5" style="background-color: #922c17;">
    <div class="container py-5">
        <div class="pb-4 mb-4" style="border-bottom: 1px solid #922c17 ;">
            <div class="row g-4">                                  
            <div class="col-lg-3 col-md-6">
                <div class="footer-item">
                    <h4 class="text-light mb-3">Contact</h4>
                    <p>Address: 91 Ademola Adetokunbo Crescent<br>
                        Wuse 2, Abuja<br>
                        Nigeria.<br><br></p>
                    <p>Email: obidientmmcsl@gmail.com</p>
                    <p>Phone: +2348034521334, <br> +1 210 6395585 </p>
                    <p>Payment Accepted</p>
                    <img src="img/payment.png" class="img-fluid" alt="">
                </div>
            </div>
        </div>
    </div>
</div>


        
     <!-- JavaScript Libraries -->
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
     <script src="{% static 'assets/lib/easing/easing.min.js' %}"></script>
     <script src="{% static 'assets/lib/waypoints/waypoints.min.js' %}"></script>
     <script src="{% static 'assets/lib/lightbox/js/lightbox.min.js' %}"></script>
     <script src="{% static 'assets/lib/owlcarousel/owl.carousel.min.js' %}"></script>
 
     <!-- Template Javascript -->
     <script src="{% static 'assets/js/ecom.js' %}"></script>
    </body>

</html>

templates/ecommerce/search.html
{% extends 'ecommerce/nav/productNav.html' %}

{% block content %}

<div class="row py-1 mt-5" data-aos="zoom-out" data-aos-delay="100">
<h1 class="mr-3 text-danger" style="border-radius:16px">Search Result</h1>
</div>
<div class="row shadow border border-rounded" data-aos="zoom-out" data-aos-delay="100">

<ul>
  
  <div class="row d-flex justify-content-center">
  <div class="col">
  <div class="filtering">
  <div class="ml-4 row">
  {% for items in object_list %}
  <div class="col py-2 mr-3">
  <a href="{{items.get_absolute_url}}">
  <img src="{{items.image.url}}" width="150px" height="150px" style="border-radius:10px"></a>
  <p><a href="{{ items.get_absolute_url }}"><h3 style="text-decoration:none; color:red;">{{items.name}}</h3></a><br>
  </div>
  </div>
  </div>
  </div>

  {% empty %}
    <li>Item not available at the moment</li>
  {% endfor %}

{% endblock %}